#############################################################################
# Makefile for building: libMyUTD.so
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  MyUTD.pro
# Template: app
# Command: E:\Qt\5.8\android_armv7\bin\qmake.exe -o Makefile MyUTD.pro -spec android-g++
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = E:\Programming\android-sdk\ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-gcc
CXX           = E:\Programming\android-sdk\ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_LOCATION_LIB -DQT_QUICKCONTROLS2_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB
CFLAGS        = -fstack-protector-strong -DANDROID -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -fno-builtin-memmove --sysroot=E:\Programming\android-sdk\ndk-bundle/platforms/android-16/arch-arm/ -Os -mthumb -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -fstack-protector-strong -DANDROID -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -fno-builtin-memmove --sysroot=E:\Programming\android-sdk\ndk-bundle/platforms/android-16/arch-arm/ -O2 -Os -mthumb -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I..\..\..\Qt\5.8\android_armv7\include -I..\..\..\Qt\5.8\android_armv7\include\QtLocation -I..\..\..\Qt\5.8\android_armv7\include\QtQuickControls2 -I..\..\..\Qt\5.8\android_armv7\include\QtQuick -I..\..\..\Qt\5.8\android_armv7\include\QtGui -I..\..\..\Qt\5.8\android_armv7\include\QtQml -I..\..\..\Qt\5.8\android_armv7\include\QtNetwork -I..\..\..\Qt\5.8\android_armv7\include\QtPositioning -I..\..\..\Qt\5.8\android_armv7\include\QtConcurrent -I..\..\..\Qt\5.8\android_armv7\include\QtCore -I. -I..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include -I..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include -I..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include -I..\..\..\Qt\5.8\android_armv7\mkspecs\android-g++
QMAKE         = E:\Qt\5.8\android_armv7\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
TAR           = 
COMPRESS      = 
DISTNAME      = libMyUTD.so1.0.0
DISTDIR = E:\Programming\Projects\MyUTD\.tmp\libMyUTD.so1.0.0
LINK          = E:\Programming\android-sdk\ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-g++
LFLAGS        = --sysroot=E:\Programming\android-sdk\ndk-bundle/platforms/android-16/arch-arm/ -Wl,-soname,libMyUTD.so -Wl,-rpath=E:/Qt/5.8/android_armv7/lib -Wl,-rpath-link=E:/Qt/5.8/android_armv7/lib -Wl,--no-undefined -Wl,-z,noexecstack -shared
LIBS          = $(SUBLIBS) -LE:\Programming\android-sdk\ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a -LE:\Programming\android-sdk\ndk-bundle/platforms/android-16/arch-arm//usr/lib -Le:/programming/android-sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x -LE:/Qt/5.8/android_armv7/lib -lQt5Location -Lc:/utils/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a -Lc:/utils/android-ndk-r10e/platforms/android-9/arch-arm//usr/lib -Lc:/utils/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/windows/bin/../lib/gcc/arm-linux-androideabi/4.9 -LE:\Qt\5.8\android_armv7/lib -lQt5QuickControls2 -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5Positioning -lQt5Concurrent -lQt5Core -lGLESv2 -lgnustl_shared -llog -lz -lm -ldl -lc -lgcc
AR            = E:\Programming\android-sdk\ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-ar cqs
RANLIB        = E:\Programming\android-sdk\ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-ranlib
SED           = $(QMAKE) -install sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp qrc_qml.cpp
OBJECTS       = main.obj \
		qrc_qml.obj
DIST          = android\AndroidManifest.xml \
		android\gradle\wrapper\gradle-wrapper.jar \
		android\gradlew \
		android\res\values\libs.xml \
		android\build.gradle \
		android\gradle\wrapper\gradle-wrapper.properties \
		android\gradlew.bat  main.cpp
QMAKE_TARGET  = libMyUTD.so
DESTDIR       = 
TARGET        = libMyUTD.so


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MyUTD.pro ..\..\..\Qt\5.8\android_armv7\mkspecs\android-g++\qmake.conf ..\..\..\Qt\5.8\android_armv7\mkspecs\features\spec_pre.prf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\common\unix.conf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\common\linux.conf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\common\sanitize.conf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\common\gcc-base.conf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\common\gcc-base-unix.conf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\qdevice.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\features\device_config.prf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\common\android-base-head.conf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\qconfig.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dcore.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dcore_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dextras.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dextras_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dinput.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dinput_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dlogic.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dlogic_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dquick.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dquick_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dquickextras.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dquickinput.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dquickrender.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3drender.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3drender_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_androidextras.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_androidextras_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_charts.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_charts_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_clucene_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_core.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_core_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_datavisualization.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_datavisualization_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_egl_support_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_fb_support_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_gamepad.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_gamepad_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_gui.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_help.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_help_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_input_support_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_location.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_location_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_network.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_network_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_networkauth.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_networkauth_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_nfc.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_opengl.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_openglextensions.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_openglextensions_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_positioning.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_positioning_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_purchasing.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_purchasing_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_qml.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_qmldebug_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_quick.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_quickcontrols2.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_script.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_script_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_scripttools.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_scripttools_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_scxml.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_scxml_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_sensors.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_sensors_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_serialbus.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_serialbus_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_serialport.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_serialport_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_service_support_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_sql.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_svg.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_testlib.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_texttospeech.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_texttospeech_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_theme_support_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_uiplugin.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_uitools.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_webchannel.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_webchannel_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_websockets.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_websockets_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_webview.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_webview_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_widgets.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_xml.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_zlib_private.pri \
		..\..\..\Qt\5.8\android_armv7\mkspecs\features\qt_functions.prf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\features\qt_config.prf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\common\android-base-tail.conf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\android-g++\qmake.conf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\features\spec_post.prf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\features\exclusive_builds.prf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\features\toolchain.prf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\features\default_pre.prf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\features\resolve_config.prf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\features\default_post.prf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\features\android\android.prf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\features\android\android_deployment_settings.prf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\features\warn_on.prf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\features\qt.prf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\features\resources.prf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\features\moc.prf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\features\unix\opengl.prf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\features\unix\thread.prf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\features\qmake_use.prf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\features\file_copies.prf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\features\testcase_targets.prf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\features\exceptions.prf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\features\yacc.prf \
		..\..\..\Qt\5.8\android_armv7\mkspecs\features\lex.prf \
		MyUTD.pro \
		qml.qrc \
		..\..\..\Qt\5.8\android_armv7\lib\libQt5Location.prl \
		..\..\..\Qt\5.8\android_armv7\lib\libQt5QuickControls2.prl \
		..\..\..\Qt\5.8\android_armv7\lib\libQt5Quick.prl \
		..\..\..\Qt\5.8\android_armv7\lib\libQt5Gui.prl \
		..\..\..\Qt\5.8\android_armv7\lib\libQt5Qml.prl \
		..\..\..\Qt\5.8\android_armv7\lib\libQt5Network.prl \
		..\..\..\Qt\5.8\android_armv7\lib\libQt5Positioning.prl \
		..\..\..\Qt\5.8\android_armv7\lib\libQt5Concurrent.prl \
		..\..\..\Qt\5.8\android_armv7\lib\libQt5Core.prl
	$(QMAKE) -o Makefile MyUTD.pro -spec android-g++
..\..\..\Qt\5.8\android_armv7\mkspecs\features\spec_pre.prf:
..\..\..\Qt\5.8\android_armv7\mkspecs\common\unix.conf:
..\..\..\Qt\5.8\android_armv7\mkspecs\common\linux.conf:
..\..\..\Qt\5.8\android_armv7\mkspecs\common\sanitize.conf:
..\..\..\Qt\5.8\android_armv7\mkspecs\common\gcc-base.conf:
..\..\..\Qt\5.8\android_armv7\mkspecs\common\gcc-base-unix.conf:
..\..\..\Qt\5.8\android_armv7\mkspecs\qdevice.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\features\device_config.prf:
..\..\..\Qt\5.8\android_armv7\mkspecs\common\android-base-head.conf:
..\..\..\Qt\5.8\android_armv7\mkspecs\qconfig.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dcore.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dcore_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dextras.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dextras_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dinput.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dinput_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dlogic.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dlogic_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dquick.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dquick_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dquickextras.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dquickextras_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dquickinput.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dquickinput_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dquickrender.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3dquickrender_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3drender.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_3drender_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_accessibility_support_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_androidextras.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_androidextras_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_charts.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_charts_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_clucene_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_core.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_core_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_datavisualization.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_datavisualization_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_egl_support_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_fb_support_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_gamepad.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_gamepad_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_gui.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_gui_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_help.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_help_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_input_support_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_location.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_location_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_multimedia.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_network.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_network_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_networkauth.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_networkauth_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_nfc.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_packetprotocol_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_positioning.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_purchasing.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_purchasing_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_qml.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_qml_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_qmldebug_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_qmltest.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_quick.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_quick_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_quickcontrols2.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_script.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_script_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_scripttools.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_scripttools_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_scxml.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_scxml_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_sensors.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_serialbus.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_serialbus_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_serialport.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_service_support_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_sql.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_sql_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_svg.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_svg_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_texttospeech.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_texttospeech_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_theme_support_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_uiplugin.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_uitools.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_webchannel.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_webchannel_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_websockets.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_websockets_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_webview.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_webview_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_xml.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_xml_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\modules\qt_lib_zlib_private.pri:
..\..\..\Qt\5.8\android_armv7\mkspecs\features\qt_functions.prf:
..\..\..\Qt\5.8\android_armv7\mkspecs\features\qt_config.prf:
..\..\..\Qt\5.8\android_armv7\mkspecs\common\android-base-tail.conf:
..\..\..\Qt\5.8\android_armv7\mkspecs\android-g++\qmake.conf:
..\..\..\Qt\5.8\android_armv7\mkspecs\features\spec_post.prf:
..\..\..\Qt\5.8\android_armv7\mkspecs\features\exclusive_builds.prf:
..\..\..\Qt\5.8\android_armv7\mkspecs\features\toolchain.prf:
..\..\..\Qt\5.8\android_armv7\mkspecs\features\default_pre.prf:
..\..\..\Qt\5.8\android_armv7\mkspecs\features\resolve_config.prf:
..\..\..\Qt\5.8\android_armv7\mkspecs\features\default_post.prf:
..\..\..\Qt\5.8\android_armv7\mkspecs\features\android\android.prf:
..\..\..\Qt\5.8\android_armv7\mkspecs\features\android\android_deployment_settings.prf:
..\..\..\Qt\5.8\android_armv7\mkspecs\features\warn_on.prf:
..\..\..\Qt\5.8\android_armv7\mkspecs\features\qt.prf:
..\..\..\Qt\5.8\android_armv7\mkspecs\features\resources.prf:
..\..\..\Qt\5.8\android_armv7\mkspecs\features\moc.prf:
..\..\..\Qt\5.8\android_armv7\mkspecs\features\unix\opengl.prf:
..\..\..\Qt\5.8\android_armv7\mkspecs\features\unix\thread.prf:
..\..\..\Qt\5.8\android_armv7\mkspecs\features\qmake_use.prf:
..\..\..\Qt\5.8\android_armv7\mkspecs\features\file_copies.prf:
..\..\..\Qt\5.8\android_armv7\mkspecs\features\testcase_targets.prf:
..\..\..\Qt\5.8\android_armv7\mkspecs\features\exceptions.prf:
..\..\..\Qt\5.8\android_armv7\mkspecs\features\yacc.prf:
..\..\..\Qt\5.8\android_armv7\mkspecs\features\lex.prf:
MyUTD.pro:
qml.qrc:
..\..\..\Qt\5.8\android_armv7\lib\libQt5Location.prl:
..\..\..\Qt\5.8\android_armv7\lib\libQt5QuickControls2.prl:
..\..\..\Qt\5.8\android_armv7\lib\libQt5Quick.prl:
..\..\..\Qt\5.8\android_armv7\lib\libQt5Gui.prl:
..\..\..\Qt\5.8\android_armv7\lib\libQt5Qml.prl:
..\..\..\Qt\5.8\android_armv7\lib\libQt5Network.prl:
..\..\..\Qt\5.8\android_armv7\lib\libQt5Positioning.prl:
..\..\..\Qt\5.8\android_armv7\lib\libQt5Concurrent.prl:
..\..\..\Qt\5.8\android_armv7\lib\libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile MyUTD.pro -spec android-g++

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`\$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@if not exist $(DISTDIR) mkdir $(DISTDIR) & if not exist $(DISTDIR) exit 1
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)\
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)\
	$(COPY_FILE) --parents ..\..\..\Qt\5.8\android_armv7\mkspecs\features\data\dummy.cpp $(DISTDIR)\
	$(COPY_FILE) --parents main.cpp $(DISTDIR)\


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		..\..\..\Qt\5.8\android_armv7\bin\rcc.exe \
		Page1Form.ui.qml \
		Page1.qml \
		qtquickcontrols2.conf \
		main.qml
	E:\Qt\5.8\android_armv7\bin\rcc.exe -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ..\..\..\Qt\5.8\android_armv7\mkspecs\features\data\dummy.cpp
	E:\Programming\android-sdk\ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-g++ -fstack-protector-strong -DANDROID -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -fno-builtin-memmove --sysroot=E:\Programming\android-sdk\ndk-bundle/platforms/android-16/arch-arm/ -O2 -Os -mthumb -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ..\..\..\Qt\5.8\android_armv7\mkspecs\features\data\dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean 

####### Compile

main.obj: main.cpp ..\..\..\Qt\5.8\android_armv7\include\QtGui\QGuiApplication \
		..\..\..\Qt\5.8\android_armv7\include\QtGui\qguiapplication.h \
		..\..\..\Qt\5.8\android_armv7\include\QtGui\qtguiglobal.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qglobal.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\type_traits \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\c++0x_warning.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\c++config.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\os_defines.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\cpu_defines.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\cstdint \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\stdint.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\_types.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\machine\_types.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\_wchar_limits.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\android\api-level.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\cstddef \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qconfig-bootstrapped.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qconfig.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qtcore-config.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qsystemdetection.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qprocessordetection.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qcompilerdetection.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\utility \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_relops.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_pair.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\move.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\concept_check.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\boost_concept_check.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_iterator_base_types.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\initializer_list \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\algorithm \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_algobase.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\functexcept.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\exception_defines.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\cpp_type_traits.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\ext\type_traits.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\ext\numeric_traits.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_iterator_base_funcs.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\debug.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\macros.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\functions.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_function.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\backward\binders.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\formatter.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\typeinfo \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\exception \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\atomic_lockfree_defines.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\exception_ptr.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\nested_exception.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\hash_bytes.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_iterator.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\ptr_traits.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\predefined_ops.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\algobase.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\base.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\features.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\basic_iterator.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\parallel.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\compiletime_settings.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\cstdio \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\stdio.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\cdefs.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\cdefs_elf.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\types.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\linux\posix_types.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\linux\stddef.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\linux\compiler.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\asm\posix_types.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\asm\types.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\linux\types.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\machine\kernel.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\sysmacros.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\types.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\cstdlib \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\stdlib.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\string.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\malloc.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\alloca.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\strings.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\memory.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\limits \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\cstdint \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\tags.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\settings.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\algorithmfwd.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\find.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\compatibility.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sched.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\time.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\linux\time.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\equally_split.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\find_selectors.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_algo.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\algorithmfwd.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_heap.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_tempbuf.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_construct.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\new \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\ext\alloc_traits.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\alloc_traits.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\memoryfwd.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\allocator.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\c++allocator.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\ext\new_allocator.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\random \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\cmath \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\math.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\limits.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\limits.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\linux\limits.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\machine\internal_types.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\machine\limits.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\syslimits.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\asm\page.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\string \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stringfwd.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\char_traits.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\postypes.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\cwchar \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\wchar.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\time.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\asm\siginfo.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\asm-generic\siginfo.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\localefwd.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\c++locale.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\clocale \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\locale.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\iosfwd \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\cctype \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\ctype.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\ostream_insert.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\cxxabi_forced.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\range_access.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\basic_string.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\ext\atomicity.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\gthr.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\gthr-default.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\pthread.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\signal.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\asm\signal.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\asm-generic\signal.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\asm\sigcontext.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\ucontext.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\user.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\unistd.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\select.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\sysconf.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\linux\capability.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\pathconf.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\atomic_word.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\ext\string_conversions.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\cerrno \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\errno.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\linux\errno.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\asm\errno.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\asm-generic\errno.h \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\asm-generic\errno-base.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\functional_hash.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\basic_string.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\random.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\vector \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_uninitialized.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_vector.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_bvector.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\vector.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\vector \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_sequence.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_base.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\ext\concurrence.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_sequence.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_iterator.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_iterator.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\vector \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\base.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\functional \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tuple \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\array \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\stdexcept \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\array \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\array \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\uses_allocator.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_hash_func.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_node.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_trace.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\unordered_map \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\ext\aligned_buffer.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\hashtable.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\hashtable_policy.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\unordered_map.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\unordered_map \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_unordered_container.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_unordered_base.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_unordered_container.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_local_iterator.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_local_iterator.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\unordered_map \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\unordered_base.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\unordered_map \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\type_traits \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\functional_hash.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\hashtable.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\hashtable_policy.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\unordered_map.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\fstream \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\istream \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\ios \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\ios_base.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\locale_classes.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\locale_classes.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\streambuf \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\streambuf.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\basic_ios.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\locale_facets.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\cwctype \
		..\..\android-sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\wctype.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\ctype_base.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\streambuf_iterator.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\ctype_inline.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\locale_facets.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\basic_ios.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\ostream \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\ostream.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\istream.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\codecvt.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\basic_file.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\c++io.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\fstream.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_algos.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_state.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_hashtable_size.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_container_size.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\sstream \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\sstream.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_map_to_unordered_map.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_vector_size.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_vector_to_list.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_list_to_slist.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_list_to_vector.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\iterator_tracker.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\opt_random.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\random.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\numeric \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_numeric.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\numeric \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\numericfwd.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\iterator.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\for_each.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\par_loop.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\omp_loop.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\workstealing.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\random_number.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\random \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\cmath \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\gamma.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\special_function_util.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\bessel_function.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\beta_function.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\ell_integral.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\exp_integral.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\hypergeometric.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\legendre_function.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\modified_bessel_func.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\poly_hermite.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\poly_laguerre.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\riemann_zeta.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\random.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\random.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\for_each_selectors.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\partial_sum.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\algorithm \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\algo.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\sort.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\checkers.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\multiway_mergesort.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\multiway_merge.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\losertree.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\multiseq_selection.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\queue \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\deque \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_deque.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\deque.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\deque \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\deque \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_queue.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\quicksort.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\partition.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\balanced_quicksort.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\queue.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\omp_loop_static.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\search.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\random_shuffle.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\merge.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\unique_copy.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\set_operations.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qtypeinfo.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qsysinfo.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qlogging.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qflags.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qtypetraits.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qatomic.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qbasicatomic.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qatomic_bootstrap.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qgenericatomic.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qatomic_cxx11.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\atomic \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\atomic_base.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qatomic_msvc.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qglobalstatic.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qmutex.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\chrono \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\ratio \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\ctime \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\parse_numbers.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qnumeric.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qversiontagging.h \
		..\..\..\Qt\5.8\android_armv7\include\QtGui\qtgui-config.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qcoreapplication.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qstring.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qchar.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qbytearray.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qrefcount.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qnamespace.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qarraydata.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\iterator \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stream_iterator.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qstringbuilder.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qobject.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qobjectdefs.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qobjectdefs_impl.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qlist.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qalgorithms.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qiterator.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qhashfunctions.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qpair.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\list \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_list.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\list.tcc \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\list \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\list \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qbytearraylist.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qstringlist.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qregexp.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qstringmatcher.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qcoreevent.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qscopedpointer.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qmetatype.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qvarlengtharray.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qcontainerfwd.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\map \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_tree.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_map.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_multimap.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\map \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\map.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\multimap.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\map \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\map.h \
		..\..\android-sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\multimap.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qobject_impl.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qeventloop.h \
		..\..\..\Qt\5.8\android_armv7\include\QtGui\qwindowdefs.h \
		..\..\..\Qt\5.8\android_armv7\include\QtGui\qwindowdefs_win.h \
		..\..\..\Qt\5.8\android_armv7\include\QtGui\qinputmethod.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qlocale.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qvariant.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qmap.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qdebug.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qhash.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qtextstream.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qiodevice.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qvector.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qpoint.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qset.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qcontiguouscache.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qsharedpointer.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qshareddata.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qsharedpointer_impl.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qsize.h \
		..\..\..\Qt\5.8\android_armv7\include\QtQml\QQmlApplicationEngine \
		..\..\..\Qt\5.8\android_armv7\include\QtQml\qqmlapplicationengine.h \
		..\..\..\Qt\5.8\android_armv7\include\QtQml\qqmlengine.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qurl.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qurlquery.h \
		..\..\..\Qt\5.8\android_armv7\include\QtQml\qjsengine.h \
		..\..\..\Qt\5.8\android_armv7\include\QtQml\qjsvalue.h \
		..\..\..\Qt\5.8\android_armv7\include\QtQml\qtqmlglobal.h \
		..\..\..\Qt\5.8\android_armv7\include\QtQml\qtqml-config.h \
		..\..\..\Qt\5.8\android_armv7\include\QtNetwork\qtnetworkglobal.h \
		..\..\..\Qt\5.8\android_armv7\include\QtNetwork\qtnetwork-config.h \
		..\..\..\Qt\5.8\android_armv7\include\QtQml\qqml.h \
		..\..\..\Qt\5.8\android_armv7\include\QtQml\qqmlprivate.h \
		..\..\..\Qt\5.8\android_armv7\include\QtQml\qqmlparserstatus.h \
		..\..\..\Qt\5.8\android_armv7\include\QtQml\qqmlpropertyvaluesource.h \
		..\..\..\Qt\5.8\android_armv7\include\QtQml\qqmllist.h \
		..\..\..\Qt\5.8\android_armv7\include\QtCore\qmetaobject.h \
		..\..\..\Qt\5.8\android_armv7\include\QtQml\qqmlerror.h \
		..\..\..\Qt\5.8\android_armv7\include\QtQml\qqmldebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.obj main.cpp

qrc_qml.obj: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.obj qrc_qml.cpp

####### Install

install_target: first FORCE
	@if not exist $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a mkdir $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a & if not exist $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a exit 1
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a\$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a\$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

